name: Ten80
favicon: null
layout_spectrum: 0.42463314859196544
typography_spectrum: 0.38319411501288414
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.22180827893316746
  lightness: 0.09036833234131336
  saturation: 0.25670683360658586
  rhythmicContrast: 0.678867359412834
purpose: []
